// Generates the standalone, copy-in player from the real packages.
//
// Run: dart run tool/build_player.dart
//      dart run tool/build_player.dart --verify   (also type-checks the output)
//
// WHY A GENERATOR AND NOT A HAND-WRITTEN PLAYER: a second implementation of the
// evaluator is a second implementation that disagrees. Everything shipped here
// is the same source the editor runs, copied verbatim — only the *imports* are
// rewritten. If playback is right in the editor it is right in the bundle, and
// there is no third place for a trim/easing/loop bug to hide.
//
// WHAT IT DROPS: `anim_core/src/ops/**` (the editing commands) and the editor's
// overlay/draft/background painters. Both are leaves — nothing on the playback
// path imports them, which `--verify` proves rather than assumes.
//
// OUTPUT
//   dist/anim_player/            the folder a consuming app copies into lib/
//   assets/player_bundle.json    the same files as {path: contents}, so the
//                                app's download button can zip them at runtime
//                                without 250KB of escaped Dart in the build.
import 'dart:convert';
import 'dart:io';

const _outDir = 'dist/anim_player';
const _assetPath = 'assets/player_bundle.json';

const _corePkg = 'package:anim_core/anim_core.dart';

/// Core files that exist only to *edit* a document. Playback never reaches them.
bool _isEditingOnly(String relative) => relative.startsWith('ops/');

/// Render files the editor needs and a consumer must never inherit: the overlay
/// dereferences paths undo just deleted, `draft_path` is a live drawing gesture,
/// and `background_painter` wants a themed `edge` colour from the app.
const _editorOnlyRender = <String>{
  'overlay_painter.dart',
  'draft_path.dart',
  'background_painter.dart',
};

/// Core types a *consumer* of the player legitimately names.
///
/// Curated rather than a blanket re-export, and the omissions are the point:
/// `Animation`, `StrokeCap` and `StrokeJoin` exist in both this domain and
/// Flutter, so exporting them would make `import 'anim_player.dart'` alongside
/// `material.dart` a compile error in the user's app for a name they never
/// asked for. Anyone who needs them can import the inner barrel with a prefix.
const _publicCoreNames = <String>[
  'Document',
  'DocumentException',
  'DecodeWarning',
  'onDecodeWarning',
  'AnimationId',
  'NodeId',
  'LoopMode',
  'Vec2',
  'Rgba',
  'kSchemaVersion',
];

void main(List<String> args) {
  final root = Directory.current.path;
  if (!File('$root/packages/anim_core/lib/anim_core.dart').existsSync()) {
    stderr.writeln('run from the repo root');
    exit(2);
  }

  final files = <String, String>{}; // output path -> contents

  // ---- 1. anim_core, minus the editing ops -------------------------------
  final coreSrc = Directory('packages/anim_core/lib/src');
  for (final e in coreSrc.listSync(recursive: true)) {
    if (e is! File || !e.path.endsWith('.dart')) continue;
    final rel = e.path.split('packages/anim_core/lib/src/').last;
    if (_isEditingOnly(rel)) continue;
    // Structure is mirrored exactly, so every '../affine.dart' inside core
    // still resolves without touching a single core import.
    files['src/core/src/$rel'] = e.readAsStringSync();
  }
  files['src/core/core.dart'] = _coreBarrel();

  // ---- 2. anim_render, playback only -------------------------------------
  final renderSrc = Directory('packages/anim_render/lib/src');
  for (final e in renderSrc.listSync()) {
    if (e is! File || !e.path.endsWith('.dart')) continue;
    final name = e.path.split('/').last;
    if (_editorOnlyRender.contains(name)) continue;
    files['src/render/$name'] = _rewriteRenderImports(e.readAsStringSync());
  }

  // ---- 3. the public barrel and the docs ---------------------------------
  files['anim_player.dart'] = _publicBarrel();
  files['README.md'] = _readme();

  _write(files);
  stdout.writeln('wrote ${files.length} files to $_outDir/');
  stdout.writeln('wrote $_assetPath');

  if (args.contains('--verify')) _verify(files);
}

/// `anim_core.dart` with the ops exports removed.
///
/// Rebuilt from the real barrel rather than hand-listed, so a file added to
/// anim_core ships in the player automatically instead of silently missing.
String _coreBarrel() {
  final source = File('packages/anim_core/lib/anim_core.dart').readAsStringSync();
  final kept = source
      .split('\n')
      .where((l) => !RegExp(r"^export 'src/ops/").hasMatch(l))
      .join('\n');
  return '// GENERATED by tool/build_player.dart — do not edit.\n'
      '// anim_core, minus the editing ops.\n$kept';
}

/// Point a render file at the bundled core instead of at the pub package,
/// keeping whatever `show`/`hide`/`as` followed it.
///
/// The combinators are load-bearing: `paint_translation.dart` imports the
/// barrel twice, once `hide StrokeCap, StrokeJoin` and once `as anim`, because
/// those names mean one thing in this domain and another in dart:ui. Preserving
/// each file's own import scoping verbatim is exactly why the bundle is a
/// folder and not one flattened file.
String _rewriteRenderImports(String source) => source
    .replaceAll("'$_corePkg'", "'../core/core.dart'")
    .replaceAll('"$_corePkg"', "'../core/core.dart'");

String _publicBarrel() => '''
// GENERATED by tool/build_player.dart — do not edit.
//
// The standalone player. Copy this folder into your app's `lib/` and import
// this file; there is no package to add and no dependency beyond Flutter.
//
//   import 'anim_player/anim_player.dart';
//
//   AnimPlayer.fromJson(jsonString)
//
// See README.md in this folder.
library;

export 'src/render/anim_player.dart' show AnimPlayer;

// Curated on purpose — see `_publicCoreNames` in tool/build_player.dart for why
// `Animation`, `StrokeCap` and `StrokeJoin` are NOT here.
export 'src/core/core.dart' show ${_publicCoreNames.join(', ')};
''';

String _readme() => '''
# anim_player

Plays animations exported from the Drawing Animation Tool. **No package to
install** — this folder *is* the player.

## Install

1. Copy this whole `anim_player/` folder into your app's `lib/`.
2. That's it. It depends on nothing outside the Flutter SDK.

## Use

```dart
import 'package:flutter/material.dart';
import 'anim_player/anim_player.dart';

class Spinner extends StatelessWidget {
  const Spinner({super.key, required this.json});
  final String json; // the editor's "Export .json" output

  @override
  Widget build(BuildContext context) => SizedBox(
        width: 96,
        height: 96,
        child: AnimPlayer.fromJson(json),
      );
}
```

Loading it from an asset:

```dart
FutureBuilder<String>(
  future: DefaultAssetBundle.of(context).loadString('assets/icon.json'),
  builder: (context, snap) => snap.hasData
      ? AnimPlayer.fromJson(snap.data!)
      : const SizedBox.shrink(),
)
```

## Options

| argument | default | meaning |
|---|---|---|
| `animationId` | document default | which animation to play |
| `playing` | `true` | `false` holds the current frame (pause, not stop) |
| `speed` | `1.0` | wall-clock multiplier |
| `drawBackground` | `true` | fill the artboard with the authored background |
| `clipToArtboard` | `true` | clip geometry at the board edge |
| `onCompleted` | – | fires once when a `LoopMode.once` animation ends |
| `errorBuilder` | empty box | shown if the JSON will not decode |

`AnimPlayer` sizes itself to its constraints and letterboxes the artboard
inside them, so it behaves like any other box. In an unbounded axis it falls
back to the artboard's authored size.

## What is in here

Generated from the editor's own source by `tool/build_player.dart` — the same
evaluator, the same painter, the same easing and loop maths the editor uses. The
editing commands and the editor's overlay layers are stripped.

Regenerate after changing the packages; do not hand-edit these files.
''';

void _write(Map<String, String> files) {
  final out = Directory(_outDir);
  if (out.existsSync()) out.deleteSync(recursive: true);
  files.forEach((path, contents) {
    final f = File('$_outDir/$path')..parent.createSync(recursive: true);
    f.writeAsStringSync(contents);
  });

  // One asset, not a directory tree: Flutter's asset declarations do not
  // recurse, so a folder here would mean a pubspec edit every time the
  // generator adds a file. A single JSON manifest is one pubspec line forever.
  File(_assetPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(
        const JsonEncoder.withIndent('  ').convert(Map.fromEntries(
      files.entries.toList()..sort((a, b) => a.key.compareTo(b.key)),
    )));
}

/// Type-check the bundle the way a consumer would: as plain files in a bare
/// Flutter app, with no path dependency back to this repo.
///
/// This is what turns "ops is a leaf" from a claim into a fact — if anything on
/// the playback path still reached into the stripped files, this fails.
void _verify(Map<String, String> files) {
  final tmp = Directory.systemTemp.createTempSync('anim_player_verify');
  stdout.writeln('verifying in ${tmp.path} ...');
  try {
    File('${tmp.path}/pubspec.yaml').writeAsStringSync('''
name: anim_player_verify
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
''');
    files.forEach((path, contents) {
      if (!path.endsWith('.dart')) return;
      File('${tmp.path}/lib/anim_player/$path')
        ..parent.createSync(recursive: true)
        ..writeAsStringSync(contents);
    });

    final get = Process.runSync('flutter', ['pub', 'get'],
        workingDirectory: tmp.path);
    if (get.exitCode != 0) {
      stderr.writeln('pub get failed:\n${get.stderr}');
      exit(1);
    }
    final analyze = Process.runSync('flutter', ['analyze', '--no-pub'],
        workingDirectory: tmp.path);
    stdout.writeln(analyze.stdout);
    if (analyze.exitCode != 0) {
      stderr.writeln(analyze.stderr);
      stderr.writeln('VERIFY FAILED — the bundle does not type-check standalone');
      exit(1);
    }
    stdout.writeln('verify ok — bundle type-checks as a standalone copy-in');
  } finally {
    tmp.deleteSync(recursive: true);
  }
}
